# Use container system
sudo: false

# Cache OpenSSL build
cache:
  directories:
  - $HOME/build/dependencies/openssl

# Build matrix
language: c
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: ENFORCE_OPENSSL=0
# TODO: Re-enable once trusty upgraded to OpenSSL >= 1.0.2
#    - os: linux
#      dist: trusty
#      compiler: gcc
#      env: ENFORCE_OPENSSL=1
    - os: linux
      dist: trusty
      compiler: clang
      env: ENFORCE_OPENSSL=0
# TODO: Re-enable once trusty upgraded to OpenSSL >= 1.0.2
#    - os: linux
#      dist: trusty
#      compiler: clang
#      env: ENFORCE_OPENSSL=1
# TODO: Re-enable once https://github.com/NEAT-project/usrsctp-neat/issues/6 has been resolved
#    - os: linux
#      dist: precise
#      compiler: gcc
#      env: ENFORCE_OPENSSL=0
# TODO: Re-enable once precise upgraded to OpenSSL >= 1.0.2
#    - os: linux
#      dist: precise
#      compiler: gcc
#      env: ENFORCE_OPENSSL=1
# TODO: Re-enable once https://github.com/NEAT-project/usrsctp-neat/issues/6 has been resolved
#    - os: linux
#      dist: precise
#      compiler: clang
#      env: ENFORCE_OPENSSL=0
# TODO: Re-enable once precise upgraded to OpenSSL >= 1.0.2
#    - os: linux
#      dist: precise
#      compiler: clang
#      env: ENFORCE_OPENSSL=1
    - os: osx
      compiler: gcc
      env: ENFORCE_OPENSSL=0
#    - os: osx
#      compiler: gcc
#      env: ENFORCE_OPENSSL=1
    - os: osx
      compiler: clang
      env: ENFORCE_OPENSSL=0
#    - os: osx
#      compiler: clang
#      env: ENFORCE_OPENSSL=1

# Linux dependencies
addons:
  apt:
    packages:
    - git
    - pkg-config
    - libssl-dev

# OSX dependencies
before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      which openssl
      echo $PATH
      brew update;
      brew install --force openssl;
      export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:${PKG_CONFIG_PATH}
      find /usr/local/Cellar -name 'pkgconfig' -type d
      find /usr/local/Cellar -name 'libcrypto*' -type f
      find /usr/local/Cellar -name 'libssl*' -type f
    fi

# Make dependencies
install:
  - ./make-dependencies.sh

# Set environment vars
before_script:
  - export BUILD_PATH=${PWD}/build
  - export PKG_CONFIG_PATH=${BUILD_PATH}/prefix/lib/pkgconfig:${PKG_CONFIG_PATH}
  - export LD_LIBRARY_PATH=${BUILD_PATH}/prefix/lib:${LD_LIBRARY_PATH}
  - export PATH=${BUILD_PATH}/prefix/bin:${PATH}
  - echo $PKG_CONFIG_PATH
  - ls -l ${BUILD_PATH}/prefix/lib
  - ls -l ${BUILD_PATH}/prefix/lib/pkgconfig
  - pkg-config --modversion openssl
  - pkg-config --libs openssl

# Install library and run tests
script:
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=${BUILD_PATH}/prefix .. && make install
  - "echo TODO: make test"
#  - make test
